### ISSUE TITLE
IDA 9.0 Support

### ISSUE THREAD

**Issue by adryd325** [MotoFanRu/M-CORE_IDA-Pro#1]
Looks like this doesn't want to work with IDA 9.0

Gives the following error
```
LoadLibrary(C:\Program Files\IDA Professional 9.0\procs\mcore.dll) error: The specified procedure could not be found.
```

**Comment by adryd325** [comment]
Building against IDA 9's SDK gets upset that ph in out.cpp is undefined

```
Build FAILED.

"C:\Users\adryd\_\M-CORE_IDA-Pro\mcore_ida.sln" (default target) (1) ->
"C:\Users\adryd\_\M-CORE_IDA-Pro\mcore_ida.vcxproj.metaproj" (default target) (3) ->
"C:\Users\adryd\_\M-CORE_IDA-Pro\mcore_ida.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\Users\adryd\_\M-CORE_IDA-Pro\out.cpp(15,34): error C2065: 'ph': undeclared identifier [C:\Users\adryd\_\M-CORE_IDA-Pro\mcore_ida.vcxproj]
  C:\Users\adryd\_\M-CORE_IDA-Pro\out.cpp(16,27): error C2065: 'ph': undeclared identifier [C:\Users\adryd\_\M-CORE_IDA-Pro\mcore_ida.vcxproj]
  C:\Users\adryd\_\M-CORE_IDA-Pro\out.cpp(25,34): error C2065: 'ph': undeclared identifier [C:\Users\adryd\_\M-CORE_IDA-Pro\mcore_ida.vcxproj]
  C:\Users\adryd\_\M-CORE_IDA-Pro\out.cpp(26,15): error C2065: 'ph': undeclared identifier [C:\Users\adryd\_\M-CORE_IDA-Pro\mcore_ida.vcxproj]
  C:\Users\adryd\_\M-CORE_IDA-Pro\out.cpp(30,19): error C2065: 'ph': undeclared identifier [C:\Users\adryd\_\M-CORE_IDA-Pro\mcore_ida.vcxproj]
  C:\Users\adryd\_\M-CORE_IDA-Pro\out.cpp(127,47): error C2065: 'ash': undeclared identifier [C:\Users\adryd\_\M-CORE_IDA-Pro\mcore_ida.vcxproj]

    0 Warning(s)
    6 Error(s)
```

**Comment by adryd325** [comment]
tried capitalizing ASH and PH since I found these definitions 

![Image](https://github.com/user-attachments/assets/962fe1ff-f915-4b15-922c-e009dcbfe5f0)

It compiles but then crashes ida, I presume cause this is not what ash and ph are supposed to be. Gonna hope that someone who actually knows C can take this on

**Comment by adryd325** [comment]
Fixed in 658029a694968269959f76f16d68784dc7d6c118
